=begin
#API Marketplace Grupo Netshoes

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::InlineResponse200ItemsAttributes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse200ItemsAttributes' do
  before do
    # run before each test
    @instance = SwaggerClient::InlineResponse200ItemsAttributes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse200ItemsAttributes' do
    it 'should create an instact of InlineResponse200ItemsAttributes' do
      expect(@instance).to be_instance_of(SwaggerClient::InlineResponse200ItemsAttributes)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "values"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

