=begin
#API Marketplace Grupo Netshoes

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/attribute_request'
require 'swagger_client/models/attribute_response'
require 'swagger_client/models/body'
require 'swagger_client/models/body_1'
require 'swagger_client/models/body_2'
require 'swagger_client/models/body_3'
require 'swagger_client/models/body_4'
require 'swagger_client/models/body_5'
require 'swagger_client/models/body_6'
require 'swagger_client/models/image_request'
require 'swagger_client/models/image_response'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_1_reviews'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_items'
require 'swagger_client/models/inline_response_200_items_attributes'
require 'swagger_client/models/inline_response_200_items_images'
require 'swagger_client/models/inline_response_200_items_links'
require 'swagger_client/models/link'
require 'swagger_client/models/list_product_response'
require 'swagger_client/models/price_request'
require 'swagger_client/models/price_response'
require 'swagger_client/models/product_request'
require 'swagger_client/models/product_response'
require 'swagger_client/models/product_status_request'
require 'swagger_client/models/product_status_response'
require 'swagger_client/models/products_attributes'
require 'swagger_client/models/products_images'
require 'swagger_client/models/review'
require 'swagger_client/models/stock_request'
require 'swagger_client/models/stock_response'

# APIs
require 'swagger_client/api/prices_api'
require 'swagger_client/api/products_api'
require 'swagger_client/api/stocks_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
